main_page:
    path:      /main
    defaults:  { _controller: AppBundle:MainPage:page }

profile_page:
      path:      /profile
      defaults:  { _controller: AppBundle:ProfilePage:page }

article_page:
      path:      /article
      defaults: {_controller: AppBundle:ArticlePage:page}