app:
    pattern: /main
    defaults:
      _controller: "AppBundle/Controller/MainPageController::PageAction"

    pattern: /chat
    defaults:
      _controller: "AppBundle/Controller/ChatPageController::PageAction"
